site_name: p1-kernel

theme:
  name: material
  #name: mkdocs
  # custom_dir: material

  # 404 page
  static_templates:
  - 404.html
    
  navigation_depth: 3
  
  # Don't include MkDocs' JavaScript
  include_search_page: true
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    # - navigation.instant
    # - navigation.sections
    - navigation.tabs
  palette:
    scheme: default
    primary: deep purple
    accent: deep purple
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

plugins:
  - search
#  - git-revision-date-localized

nav:
  - OVERVIEW: README.md
  - exp0: exp0/rpi-os.md
  - exp1: exp1/rpi-os.md
  - exp2: exp2/rpi-os.md  
  - exp3: exp3/rpi-os.md
  - exp4a: exp4a/rpi-os.md
  - exp4b: exp4b/rpi-os.md
  - exp5: exp5/rpi-os.md  
  - exp6: exp6/rpi-os.md  
  #- Device:
   # - Hikey: devices/hikey.md
    #- Odroid: devices/odroid.md
  - /qemu: qemu.md    
  - /gdb: gdb.md
  - /aarch64: cheatsheet.md
  - /ssh: ssh-proxy.md
  - /ker dump: dump.md
  - /jtag: jtag.md
  - /rpi workflow: exp1/workflow.md
